const SUPABASE_URL="https://zhhtugewxipxgyetbjqo.supabase.co";
const SUPABASE_KEY="sb_publishable_T5Uh8cM_qjhGL-h_NnmACw_y_N2gYv3";
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const ACCESS_KEY="karaca_siparis_access";
const ROLE_KEY="karaca_simple_role";
const PERSON_KEY="karaca_person_by_role";
const ROLE_LABEL={marketing:"Pazarlama",warehouse:"Depo",operations:"Operasyon",shipping:"Sevkiyat",admin:"Admin"};
const ROLE_CLASS={marketing:"role-marketing",warehouse:"role-warehouse",operations:"role-operations",shipping:"role-shipping",admin:"role-admin"};
const ROLE_META={
  marketing:["Pazarlama","Müşteri siparişini sisteme girin ve Depo'ya gönderin."],
  warehouse:["Depo","Size düşen siparişleri alın ve ilgili depo aşamasını yönetin."],
  operations:["Operasyon","Depodan tamamlanan siparişleri kontrol edip onaylayın."],
  shipping:["Sevkiyat","Hazır siparişleri görün ve sevk durumunu tamamlayın."],
  admin:["Admin","Tüm siparişleri, sorumluları ve bölüm geçişlerini uçtan uca izleyin."]
};
const el=id=>document.getElementById(id);
const fmt=x=>x?new Intl.DateTimeFormat("tr-TR",{dateStyle:"short",timeStyle:"short"}).format(new Date(x)):"-";
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let accessCode=sessionStorage.getItem(ACCESS_KEY)||"";
let orders=[];
let staff=[];
let role=localStorage.getItem(ROLE_KEY)||"marketing";
let selectedPeople=readSelectedPeople();
let view="work";
let whTab="first";
let refreshing=false;

function readSelectedPeople(){try{return JSON.parse(localStorage.getItem(PERSON_KEY)||"{}")||{}}catch{return{}}}
function saveSelectedPeople(){localStorage.setItem(PERSON_KEY,JSON.stringify(selectedPeople));}
function mapOrder(o){return {id:o.id,orderNo:o.order_no,customer:o.customer,requirements:o.requirements||[],note:o.note||"",phase:o.phase,warehouse1Status:o.warehouse1_status||"",warehouse2Status:o.warehouse2_status||"",operationStatus:o.operation_status||"",shippingStatus:o.shipping_status||"",warehouseOwner:o.warehouse_owner||"",marketingOwnerId:o.marketing_owner_id||"",warehouseOwnerId:o.warehouse_owner_id||"",operationsOwnerId:o.operations_owner_id||"",shippingOwnerId:o.shipping_owner_id||"",createdAt:o.created_at,updatedAt:o.updated_at,history:Array.isArray(o.history)?o.history:[]};}
function mapStaff(s){return {id:s.id,name:s.name,roles:Array.isArray(s.roles)?s.roles:[],active:s.active!==false,createdAt:s.created_at,updatedAt:s.updated_at};}
async function rpc(name,args){const {data,error}=await sb.rpc(name,args);if(error)throw error;return data;}
function isAuthError(err){return err&&(err.code==="42501"||/erisim|access|permission/i.test(err.message||""));}
async function validateCode(code){try{return !!(await rpc("app_login",{p_passcode:code}));}catch{return false;}}
function personById(id){return staff.find(s=>s.id===id)||null;}
function personName(id,fallback="-"){return personById(id)?.name||fallback;}
function activeStaffFor(r){return staff.filter(s=>s.active&&s.roles.includes(r)).sort((a,b)=>a.name.localeCompare(b.name,"tr"));}
function currentPerson(){const list=activeStaffFor(role);let chosen=list.find(s=>s.id===selectedPeople[role]);if(!chosen&&list.length){chosen=list[0];selectedPeople[role]=chosen.id;saveSelectedPeople();}return chosen||null;}
function renderPersonSelect(){const list=activeStaffFor(role),cur=currentPerson();el("personSelect").innerHTML=list.length?list.map(s=>`<option value="${s.id}" ${cur?.id===s.id?"selected":""}>${esc(s.name)}</option>`).join(""):`<option value="">Bu rolde aktif personel yok</option>`;el("personSelect").disabled=!list.length;el("actorPill").textContent=cur?.name||"Personel yok";}

async function refreshData(silent=false){
  if(!accessCode||refreshing)return;
  refreshing=true;
  try{
    const [orderData,staffData]=await Promise.all([rpc("app_list_orders",{p_passcode:accessCode}),rpc("app_list_staff",{p_passcode:accessCode})]);
    orders=(Array.isArray(orderData)?orderData:[]).map(mapOrder);
    staff=(Array.isArray(staffData)?staffData:[]).map(mapStaff);
    render();
    if(!silent)toast("Veriler yenilendi");
  }catch(err){console.error(err);if(isAuthError(err))lockApp("Erişim kodu geçersiz veya değiştirildi.");else if(!silent)toast("Supabase bağlantısı kurulamadı");}
  finally{refreshing=false;}
}
function lockApp(message=""){sessionStorage.removeItem(ACCESS_KEY);accessCode="";el("loginScreen").classList.remove("hidden");el("accessCodeInput").value="";if(message)toast(message);}
async function boot(){el("roleSelect").value=role;if(accessCode&&await validateCode(accessCode)){el("loginScreen").classList.add("hidden");await refreshData(true);}else lockApp();}
el("loginForm").onsubmit=async e=>{e.preventDefault();const code=el("accessCodeInput").value.trim();if(!code)return;const btn=e.currentTarget.querySelector("button");btn.disabled=true;btn.textContent="Kontrol ediliyor...";const ok=await validateCode(code);btn.disabled=false;btn.textContent="Giriş Yap";if(!ok){toast("Erişim kodu hatalı");return;}accessCode=code;sessionStorage.setItem(ACCESS_KEY,code);el("loginScreen").classList.add("hidden");await refreshData(true);toast("Sisteme bağlandı");};
el("logoutBtn").onclick=()=>lockApp();

function currentDepartment(o){if(o.phase==="warehouse1"||o.phase==="warehouse2")return"Depo";if(o.phase==="operations")return"Operasyon";if(o.phase==="shipping")return"Sevkiyat";if(o.phase==="done")return"Tamamlandı";return"Pazarlama";}
function currentStatus(o){if(o.phase==="warehouse1")return o.warehouse1Status||"Bekleniyor";if(o.phase==="operations")return o.operationStatus||"Onay Bekliyor";if(o.phase==="warehouse2")return o.warehouse2Status||"Hazırlanıyor";if(o.phase==="shipping")return o.shippingStatus||"Hazır";if(o.phase==="done")return"Sevk Edildi";return"Yeni";}
function requirementsHtml(req=[]){if(!req.length)return`<span class="chip chip-empty">Standart</span>`;return req.map(x=>`<span class="chip ${x==="Kutu"?"chip-kutu":x==="Lazer"?"chip-lazer":"chip-etiket"}">${esc(x)}</span>`).join("");}
function warehouse1Options(o){const base=["Bekleniyor","Toplanıyor","Toplandı"];if(o.requirements.includes("Kutu"))base.push("Kutu'da");if(o.requirements.includes("Lazer"))base.push("Lazer'de");if(o.requirements.includes("Etiket"))base.push("Etiket'te");base.push("Tamamlandı");return base;}
function filtered(list){const q=el("searchInput").value.trim().toLocaleLowerCase("tr-TR"),f=el("statusFilter").value;return list.filter(o=>{if(q&&!`${o.orderNo} ${o.customer} ${o.note||""}`.toLocaleLowerCase("tr-TR").includes(q))return false;if(f&&currentStatus(o)!==f)return false;return true;});}
function roleOrders(){if(role==="marketing")return orders;if(role==="warehouse")return orders.filter(o=>whTab==="first"?o.phase==="warehouse1":o.phase==="warehouse2");if(role==="operations")return orders.filter(o=>o.phase==="operations");if(role==="shipping")return orders.filter(o=>o.phase==="shipping");return orders;}
function ownerForCurrentPhase(o){if(o.phase==="warehouse1"||o.phase==="warehouse2")return personName(o.warehouseOwnerId,o.warehouseOwner||"Atanmadı");if(o.phase==="operations")return personName(o.operationsOwnerId,"Atanmadı");if(o.phase==="shipping"||o.phase==="done")return personName(o.shippingOwnerId,"Atanmadı");return personName(o.marketingOwnerId,"Atanmadı");}

function render(){
  el("roleSelect").value=role;renderPersonSelect();const meta=ROLE_META[role];el("pageTitle").textContent=meta[0];el("pageSubtitle").textContent=meta[1];
  el("rolePill").textContent=ROLE_LABEL[role];el("rolePill").className=`role-pill ${ROLE_CLASS[role]}`;
  el("newOrderBtn").classList.toggle("hidden",role!=="marketing");el("allNav").classList.toggle("hidden",role!=="admin");el("staffNav").classList.toggle("hidden",role!=="admin");el("flowNav").classList.toggle("hidden",role!=="admin");el("warehouseTabs").classList.toggle("hidden",role!=="warehouse");el("workNavLabel").textContent=role==="admin"?"Özet":"İşlerim";
  if(role!=="admin"&&view!=="work"){view="work";switchView("work",false)}
  renderStats();renderStatusFilter();renderWork();renderAll();renderStaffTable();
}
function renderStats(){let data;if(role==="admin")data=[["Toplam Sipariş",orders.length,"Tüm kayıtlar"],["Depo",orders.filter(o=>["warehouse1","warehouse2"].includes(o.phase)).length,"İki depo aşaması"],["Operasyon",orders.filter(o=>o.phase==="operations").length,"Onay süreci"],["Sevkiyat",orders.filter(o=>o.phase==="shipping").length,"Hazır siparişler"],["Aktif Personel",staff.filter(s=>s.active).length,"Tüm bölümler"]];else if(role==="marketing")data=[["Toplam Girdi",orders.length,"Pazarlama kayıtları"],["Depoda",orders.filter(o=>["warehouse1","warehouse2"].includes(o.phase)).length,"Aktif"],["Operasyonda",orders.filter(o=>o.phase==="operations").length,"Onayda"],["Sevkiyatta",orders.filter(o=>o.phase==="shipping").length,"Hazır"],["Sevk Edildi",orders.filter(o=>o.phase==="done").length,"Tamamlanan"]];else{const mine=roleOrders();data=[["Ekranımdaki",mine.length,"Aktif kayıt"],["Bekleyen",mine.filter(o=>/Bekliyor|Bekleniyor|Hazırlanıyor/.test(currentStatus(o))).length,"Aksiyon bekleyen"],["İşlemde",mine.filter(o=>/Toplanıyor|Kutu'da|Lazer'de|Etiket'te/.test(currentStatus(o))).length,"Devam eden"],["Hazır / Onay",mine.filter(o=>/Toplandı|Onaylandı|Hazır/.test(currentStatus(o))).length,"Sonraki adıma yakın"],["Aktif Personel",activeStaffFor(role).length,ROLE_LABEL[role]]];}el("stats").innerHTML=data.map(x=>`<div class="stat"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join("");}
function renderStatusFilter(){const cur=el("statusFilter").value,sts=[...new Set(roleOrders().map(currentStatus))].sort((a,b)=>a.localeCompare(b,"tr"));el("statusFilter").innerHTML=`<option value="">Tüm durumlar</option>`+sts.map(s=>`<option ${s===cur?"selected":""}>${esc(s)}</option>`).join("");}
function renderWork(){const list=filtered(roleOrders());el("workCards").innerHTML=list.length?list.map(orderCard).join(""):`<div class="empty" style="grid-column:1/-1"><b>Bu ekranda aktif sipariş yok.</b>Akışa göre yeni sipariş geldiğinde burada görünecek.</div>`;wireCards();}
function orderCard(o){const dep=currentDepartment(o),st=currentStatus(o);return `<article class="order-card"><div class="card-top"><span class="order-no">${esc(o.orderNo)}</span><span class="status-pill status-${o.phase==="warehouse1"||o.phase==="warehouse2"?"warehouse":o.phase==="operations"?"operations":o.phase==="shipping"?"shipping":o.phase==="done"?"done":"marketing"}">${esc(st)}</span></div><h3>${esc(o.customer)}</h3><div class="card-sub">${esc(dep)} · Son güncelleme ${fmt(o.updatedAt)}</div><div class="chips">${requirementsHtml(o.requirements)}</div><div class="card-grid"><div class="meta"><span>Mevcut Sorumlu</span><strong>${esc(ownerForCurrentPhase(o))}</strong></div><div class="meta"><span>Aşama</span><strong>${esc(dep)}</strong></div></div>${role==="warehouse"?warehouseControls(o):role==="operations"?operationsControls(o):role==="shipping"?shippingControls(o):`<div class="card-actions"><button class="btn small" data-detail="${o.id}">Detay</button></div>`}</article>`;}
function warehouseOwnerOptions(o){const list=activeStaffFor("warehouse");return `<option value="">Sorumlu ata</option>`+list.map(s=>`<option value="${s.id}" ${s.id===o.warehouseOwnerId?"selected":""}>${esc(s.name)}</option>`).join("");}
function warehouseControls(o){if(o.phase==="warehouse1"){const opts=warehouse1Options(o).map(s=>`<option ${s===o.warehouse1Status?"selected":""}>${s}</option>`).join("");return `<div class="inline-form"><select class="owner-select" data-owner="${o.id}">${warehouseOwnerOptions(o)}</select><button class="btn small" data-claim="${o.id}">Üzerime Al</button><select data-wh1="${o.id}">${opts}</select><button class="btn small" data-detail="${o.id}">Detay</button></div>`;}const opts=["Hazırlanıyor","Toplandı"].map(s=>`<option ${s===o.warehouse2Status?"selected":""}>${s}</option>`).join("");return `<div class="inline-form"><select class="owner-select" data-owner="${o.id}">${warehouseOwnerOptions(o)}</select><button class="btn small" data-claim="${o.id}">Üzerime Al</button><select data-wh2="${o.id}">${opts}</select><button class="btn small" data-detail="${o.id}">Detay</button></div>`;}
function operationsControls(o){const actor=currentPerson();return `<div class="staff-summary"><span>İşlemi yapan:</span><b>${esc(actor?.name||"Personel seçilmedi")}</b></div><div class="card-actions"><button class="btn small" data-detail="${o.id}">Detay</button><button class="btn success small" data-approve="${o.id}">Onayla ve Depo'ya Gönder</button></div>`;}
function shippingControls(o){const actor=currentPerson();return `<div class="staff-summary"><span>İşlemi yapan:</span><b>${esc(actor?.name||"Personel seçilmedi")}</b></div><div class="card-actions"><button class="btn small" data-detail="${o.id}">Detay</button><button class="btn success small" data-ship="${o.id}">Sevk Edildi</button></div>`;}
async function updateOrder(id,patch,eventText){try{await rpc("app_update_order",{p_passcode:accessCode,p_id:id,p_patch:patch,p_event_text:eventText});await refreshData(true);toast(eventText);}catch(err){console.error(err);toast(err.message||"Güncelleme yapılamadı");}}
function wireCards(){
  document.querySelectorAll("[data-detail]").forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));
  document.querySelectorAll("[data-owner]").forEach(sel=>sel.onchange=()=>{if(!sel.value){renderWork();return;}const name=personName(sel.value,"Personel");updateOrder(sel.dataset.owner,{warehouse_owner_id:sel.value},`Depo sorumlusu: ${name}`);});
  document.querySelectorAll("[data-claim]").forEach(b=>b.onclick=()=>{const actor=currentPerson();if(!actor){toast("Önce Depo personeli seçin");return;}updateOrder(b.dataset.claim,{warehouse_owner_id:actor.id},`${actor.name} siparişi üzerine aldı.`);});
  document.querySelectorAll("[data-wh1]").forEach(s=>s.onchange=()=>{const val=s.value;if(val==="Tamamlandı")updateOrder(s.dataset.wh1,{warehouse1_status:val,phase:"operations",operation_status:"Onay Bekliyor"},"Depo ilk aşaması tamamlandı. Sipariş Operasyona gönderildi: Onay Bekliyor");else updateOrder(s.dataset.wh1,{warehouse1_status:val},`Depo durumu: ${val}`);});
  document.querySelectorAll("[data-wh2]").forEach(s=>s.onchange=()=>{const val=s.value;if(val==="Toplandı")updateOrder(s.dataset.wh2,{warehouse2_status:val,phase:"shipping",shipping_status:"Hazır"},"Depo ikinci aşaması Toplandı. Sipariş Sevkiyat'a geçti: Hazır");else updateOrder(s.dataset.wh2,{warehouse2_status:val},`Onay sonrası Depo durumu: ${val}`);});
  document.querySelectorAll("[data-approve]").forEach(b=>b.onclick=()=>{const actor=currentPerson();if(!actor){toast("Önce Operasyon personeli seçin");return;}updateOrder(b.dataset.approve,{operations_owner_id:actor.id,operation_status:"Onaylandı",phase:"warehouse2",warehouse2_status:"Hazırlanıyor"},`${actor.name} siparişi onayladı. Sipariş tekrar Depo'ya gönderildi: Hazırlanıyor`);});
  document.querySelectorAll("[data-ship]").forEach(b=>b.onclick=()=>{const actor=currentPerson();if(!actor){toast("Önce Sevkiyat personeli seçin");return;}updateOrder(b.dataset.ship,{shipping_owner_id:actor.id,shipping_status:"Sevk Edildi",phase:"done"},`${actor.name} siparişi Sevk Edildi olarak tamamladı.`);});
}
function renderAll(){const rows=[...orders].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));el("allTable").innerHTML=rows.length?rows.map(o=>`<tr><td><strong>${esc(o.orderNo)}</strong></td><td>${esc(o.customer)}</td><td><div class="chips" style="margin:0">${requirementsHtml(o.requirements)}</div></td><td>${esc(currentDepartment(o))}</td><td><span class="status-pill status-${o.phase==="warehouse1"||o.phase==="warehouse2"?"warehouse":o.phase==="operations"?"operations":o.phase==="shipping"?"shipping":o.phase==="done"?"done":"marketing"}">${esc(currentStatus(o))}</span></td><td>${esc(personName(o.marketingOwnerId,"-"))}</td><td>${esc(personName(o.warehouseOwnerId,o.warehouseOwner||"-"))}</td><td>${esc(personName(o.operationsOwnerId,"-"))}</td><td>${esc(personName(o.shippingOwnerId,"-"))}</td><td>${fmt(o.updatedAt)}</td><td><button class="btn small" data-all-detail="${o.id}">Detay</button></td></tr>`).join(""):`<tr><td colspan="11">Henüz sipariş yok.</td></tr>`;document.querySelectorAll("[data-all-detail]").forEach(b=>b.onclick=()=>openDetail(b.dataset.allDetail));}
function openDetail(id){const o=orders.find(x=>x.id===id);if(!o)return;el("detailTitle").textContent=`${o.orderNo} · ${o.customer}`;el("detailSub").textContent=`${currentDepartment(o)} · ${currentStatus(o)}`;el("detailContent").innerHTML=`<div class="detail-grid"><div class="detail-box"><span>Müşteri</span><strong>${esc(o.customer)}</strong></div><div class="detail-box"><span>Bölüm</span><strong>${esc(currentDepartment(o))}</strong></div><div class="detail-box"><span>Durum</span><strong>${esc(currentStatus(o))}</strong></div><div class="detail-box"><span>Pazarlama</span><strong>${esc(personName(o.marketingOwnerId,"-"))}</strong></div><div class="detail-box"><span>Depo</span><strong>${esc(personName(o.warehouseOwnerId,o.warehouseOwner||"-"))}</strong></div><div class="detail-box"><span>Operasyon</span><strong>${esc(personName(o.operationsOwnerId,"-"))}</strong></div><div class="detail-box"><span>Sevkiyat</span><strong>${esc(personName(o.shippingOwnerId,"-"))}</strong></div><div class="detail-box"><span>Müşteri İsteği</span><strong>${o.requirements.length?esc(o.requirements.join(", ")):"Standart"}</strong></div><div class="detail-box"><span>Son Güncelleme</span><strong>${fmt(o.updatedAt)}</strong></div></div>${o.note?`<div class="note">${esc(o.note)}</div>`:""}<div class="timeline"><h3 style="margin:0 0 5px;font-size:12px">İşlem Geçmişi</h3>${(o.history||[]).map(h=>`<div class="timeline-item"><i></i><div><b>${esc(h.text)}</b><small>${fmt(h.at)}</small></div></div>`).join("")||"<small>Henüz işlem geçmişi yok.</small>"}</div>`;el("detailDialog").showModal();}

function roleBadges(roles){return roles.map(r=>`<span class="staff-role">${esc(ROLE_LABEL[r]||r)}</span>`).join("");}
function renderStaffTable(){if(!el("staffTable"))return;const rows=[...staff].sort((a,b)=>Number(b.active)-Number(a.active)||a.name.localeCompare(b.name,"tr"));el("staffTable").innerHTML=rows.map(s=>`<tr><td><strong>${esc(s.name)}</strong></td><td><div class="staff-role-list">${roleBadges(s.roles)}</div></td><td><span class="staff-state ${s.active?"staff-active":"staff-passive"}">${s.active?"Aktif":"Pasif"}</span></td><td>${fmt(s.updatedAt)}</td><td><button class="btn small" data-edit-staff="${s.id}">Düzenle</button></td></tr>`).join("");document.querySelectorAll("[data-edit-staff]").forEach(b=>b.onclick=()=>openStaffDialog(b.dataset.editStaff));}
function openStaffDialog(id=""){const s=id?personById(id):null;el("staffForm").reset();el("staffId").value=s?.id||"";el("staffDialogTitle").textContent=s?"Personeli Düzenle":"Personel Ekle";el("staffName").value=s?.name||"";el("staffActive").value=String(s?.active??true);document.querySelectorAll("[data-staff-role]").forEach(cb=>cb.checked=!!s?.roles.includes(cb.value));el("deactivateStaffBtn").classList.toggle("hidden",!s||!s.active);el("staffDialog").showModal();}
el("staffForm").onsubmit=async e=>{e.preventDefault();if(role!=="admin"){toast("Bu ekran yalnızca Admin içindir");return;}const roles=[...document.querySelectorAll("[data-staff-role]:checked")].map(x=>x.value);if(!roles.length){toast("En az bir rol seçin");return;}const id=el("staffId").value,name=el("staffName").value.trim(),active=el("staffActive").value==="true";const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{if(id)await rpc("app_update_staff",{p_passcode:accessCode,p_id:id,p_name:name,p_roles:roles,p_active:active});else await rpc("app_create_staff",{p_passcode:accessCode,p_name:name,p_roles:roles,p_active:active});el("staffDialog").close();await refreshData(true);toast(id?"Personel güncellendi":"Personel eklendi");}catch(err){console.error(err);toast(/unique|duplicate/i.test(err.message||"")?"Bu personel zaten var":(err.message||"Personel kaydedilemedi"));}finally{btn.disabled=false;}};
el("deactivateStaffBtn").onclick=async()=>{const id=el("staffId").value;if(!id||role!=="admin")return;if(!confirm("Personel aktif listeden çıkarılsın mı? Mevcut sipariş geçmişi korunur."))return;try{await rpc("app_deactivate_staff",{p_passcode:accessCode,p_id:id});el("staffDialog").close();await refreshData(true);toast("Personel pasife alındı");}catch(err){console.error(err);toast(err.message||"İşlem yapılamadı");}};

function switchView(v,close=true){if((v==="all"||v==="staff"||v==="flow")&&role!=="admin")v="work";view=v;document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));el(v+"View").classList.add("active");document.querySelectorAll(".nav-btn[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));el("toolbar").classList.toggle("hidden",v==="staff"||v==="flow");if(close)closeSidebar();}
el("roleSelect").onchange=()=>{role=el("roleSelect").value;localStorage.setItem(ROLE_KEY,role);whTab="first";document.querySelectorAll("[data-wh-tab]").forEach(x=>x.classList.toggle("active",x.dataset.whTab==="first"));switchView("work",false);render();};
el("personSelect").onchange=()=>{selectedPeople[role]=el("personSelect").value;saveSelectedPeople();render();};
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>switchView(b.dataset.view));
document.querySelectorAll("[data-wh-tab]").forEach(b=>b.onclick=()=>{whTab=b.dataset.whTab;document.querySelectorAll("[data-wh-tab]").forEach(x=>x.classList.toggle("active",x===b));render();});
["searchInput","statusFilter"].forEach(id=>el(id).addEventListener(id==="searchInput"?"input":"change",renderWork));
el("clearBtn").onclick=()=>{el("searchInput").value="";el("statusFilter").value="";renderWork();};
el("newOrderBtn").onclick=()=>{const actor=currentPerson();if(role!=="marketing"||!actor){toast("Pazarlama personeli seçilmeden sipariş açılamaz");return;}el("orderForm").reset();el("orderDialog").showModal();};
el("newStaffBtn").onclick=()=>{if(role!=="admin")return;openStaffDialog();};
el("orderForm").onsubmit=async e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const actor=currentPerson();if(!actor||!actor.roles.includes("marketing")){toast("Pazarlama personeli seçin");return;}const req=[];if(el("reqKutu").checked)req.push("Kutu");if(el("reqLazer").checked)req.push("Lazer");if(el("reqEtiket").checked)req.push("Etiket");const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;try{await rpc("app_create_order",{p_passcode:accessCode,p_order_no:el("orderNo").value.trim(),p_customer:el("customer").value.trim(),p_requirements:req,p_note:el("orderNote").value.trim()||null,p_marketing_owner_id:actor.id});el("orderDialog").close();await refreshData(true);toast("Sipariş Depo'ya gönderildi");}catch(err){console.error(err);toast(/duplicate|unique/i.test(err.message||"")?"Bu sipariş numarası zaten var":(err.message||"Sipariş kaydedilemedi"));}finally{btn.disabled=false;}};
el("resetBtn").onclick=()=>refreshData(false);
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>el(b.dataset.close).close());
function toast(msg){const t=el("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2600);}
const sidebar=el("sidebar");function closeSidebar(){sidebar.classList.remove("open");el("drawer").classList.remove("show")}
el("menuBtn").onclick=()=>{sidebar.classList.toggle("open");el("drawer").classList.toggle("show",sidebar.classList.contains("open"));};el("drawer").onclick=closeSidebar;
setInterval(()=>{if(accessCode&&!document.hidden&&!document.querySelector('dialog[open]')&&!document.querySelector('input:focus,select:focus,textarea:focus'))refreshData(true);},10000);
boot();
