create table if not exists private.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_username text not null,
  action text not null,
  order_id uuid,
  order_no text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function private.require_admin_credentials(
  p_username text,
  p_password text
)
returns void
language plpgsql
security definer
set search_path = private, public, extensions
as $$
begin
  if not exists (
    select 1
    from private.admin_credentials a
    where lower(a.username) = lower(trim(coalesce(p_username,'')))
      and a.active = true
      and a.password_hash = encode(digest(coalesce(p_password,''), 'sha256'), 'hex')
  ) then
    raise exception 'Admin yetkisi dogrulanamadi' using errcode = '42501';
  end if;
end;
$$;

revoke all on function private.require_admin_credentials(text,text) from public;
revoke all on function private.require_admin_credentials(text,text) from anon, authenticated;

create or replace function public.app_admin_reassign_warehouse(
  p_passcode text,
  p_username text,
  p_password text,
  p_order_id uuid,
  p_staff_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_order_no text;
  v_old_staff_id uuid;
  v_old_staff_name text;
  v_new_staff_name text;
begin
  perform private.require_app_passcode(p_passcode);
  perform private.require_admin_credentials(p_username, p_password);

  select o.order_no, o.warehouse_owner_id, coalesce(s.name, o.warehouse_owner)
    into v_order_no, v_old_staff_id, v_old_staff_name
  from public.orders o
  left join public.staff s on s.id = o.warehouse_owner_id
  where o.id = p_order_id;

  if not found then
    raise exception 'Siparis bulunamadi';
  end if;

  if p_staff_id is not null then
    perform private.require_staff_role(p_staff_id, 'warehouse');
    select name into v_new_staff_name from public.staff where id = p_staff_id;
  end if;

  update public.orders
  set warehouse_owner_id = p_staff_id,
      warehouse_owner = v_new_staff_name,
      updated_at = now()
  where id = p_order_id;

  insert into public.order_history(order_id, event_text)
  values (
    p_order_id,
    case
      when p_staff_id is null then 'Admin depo sorumlusu atamasini kaldirdi.'
      else 'Admin depo sorumlusunu ' || v_new_staff_name || ' olarak degistirdi.'
    end
  );

  insert into private.admin_audit_log(admin_username, action, order_id, order_no, details)
  values (
    trim(p_username),
    'warehouse_reassign',
    p_order_id,
    v_order_no,
    jsonb_build_object(
      'old_staff_id', v_old_staff_id,
      'old_staff_name', v_old_staff_name,
      'new_staff_id', p_staff_id,
      'new_staff_name', v_new_staff_name
    )
  );

  return true;
end;
$$;

create or replace function public.app_admin_delete_order(
  p_passcode text,
  p_username text,
  p_password text,
  p_order_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_order_no text;
  v_customer text;
  v_phase text;
  v_status text;
begin
  perform private.require_app_passcode(p_passcode);
  perform private.require_admin_credentials(p_username, p_password);

  select o.order_no, o.customer, o.phase,
         case
           when o.phase = 'warehouse1' then coalesce(o.warehouse1_status, 'Bekleniyor')
           when o.phase = 'operations' then coalesce(o.operation_status, 'Onay Bekliyor')
           when o.phase = 'warehouse2' then coalesce(o.warehouse2_status, 'Hazirlaniyor')
           when o.phase = 'shipping' then coalesce(o.shipping_status, 'Hazir')
           when o.phase = 'done' then 'Sevk Edildi'
           else 'Yeni'
         end
    into v_order_no, v_customer, v_phase, v_status
  from public.orders o
  where o.id = p_order_id;

  if not found then
    raise exception 'Siparis bulunamadi';
  end if;

  insert into private.admin_audit_log(admin_username, action, order_id, order_no, details)
  values (
    trim(p_username),
    'order_delete',
    p_order_id,
    v_order_no,
    jsonb_build_object('customer', v_customer, 'phase', v_phase, 'status', v_status)
  );

  delete from public.orders where id = p_order_id;
  return true;
end;
$$;

revoke all on function public.app_admin_reassign_warehouse(text,text,text,uuid,uuid) from public;
revoke all on function public.app_admin_delete_order(text,text,text,uuid) from public;
grant execute on function public.app_admin_reassign_warehouse(text,text,text,uuid,uuid) to anon, authenticated;
grant execute on function public.app_admin_delete_order(text,text,text,uuid) to anon, authenticated;
